# Generated by Django 4.2 on 2023-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_kategori_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('New', 'New'), ('True', 'True')], default='Now', max_length=10),
        ),
    ]
