# Generated by Django 4.2 on 2023-06-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_commenta_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentA',
            new_name='Comment',
        ),
    ]
