# Generated by Django 4.2 on 2023-06-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_rename_commenta_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentA',
        ),
    ]
