# Generated by Django 4.2 on 2023-06-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_rename_comment_commenta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentA',
            new_name='Comment',
        ),
    ]
