# Generated by Django 4.2 on 2023-06-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0014_rename_commenta_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
